name: kaggle-ventilator
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - ca-certificates=2021.5.30
  - joblib=1.0.1
  - ld_impl_linux-64=2.36.1
  - libblas=3.9.0
  - libcblas=3.9.0
  - libffi=3.4.2
  - libgcc-ng=11.2.0
  - libgfortran-ng=11.2.0
  - libgfortran5=11.2.0
  - libgomp=11.2.0
  - liblapack=3.9.0
  - libopenblas=0.3.17
  - libstdcxx-ng=11.2.0
  - libzlib=1.2.11
  - ncurses=6.2
  - numpy=1.21.2
  - openssl=3.0.0
  - pandas=1.3.3
  - pip=21.2.4
  - python=3.8.12
  - python-dateutil=2.8.2
  - python_abi=3.8
  - pytz=2021.3
  - readline=8.1
  - scikit-learn=1.0
  - scipy=1.7.1
  - setuptools=58.2.0
  - six=1.16.0
  - sqlite=3.36.0
  - threadpoolctl=3.0.0
  - tk=8.6.11
  - wheel=0.37.0
  - xz=5.2.5
  - zlib=1.2.11